In [1]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns


In [13]:
###Task 01 : Use numpy to create a 3×3 matrix of random integers between 1 and 50.
Matrix = np.random.randint(1, 50, (3, 3))
print(Matrix)

[[ 9 10  1]
 [43 41 37]
 [17 37 48]]


In [14]:
###Task 2 : Use numpy to create a 3×3 matrix of random integers between 1 and 50. With a fixed seed (`np.random.seed(10)`) to ensure reproducibility.
np.random.seed(10)
Matrix = np.random.randint(1, 50, (3, 3))
print(Matrix)

[[10 37 16]
 [ 1 29 26]
 [30 49 30]]


Task 1: Generating a Random Matrix Without a Fixed Seed
When generating a 3×3 matrix of random integers between 1 and 50 without setting a seed, the output changes every time the code runs.

This is because NumPy initializes its random number generator differently on each execution, producing a unique set of values. This behavior is useful for:

Simulations requiring fresh randomness
Data augmentation in machine learning
Generating unpredictable test cases
Task 2: Generating a Random Matrix With a Fixed Seed (np.random.seed(10))
By setting a seed (np.random.seed(10)) before generating the matrix, we ensure the same numbers are produced every time the code runs.

How It Works:
NumPy’s random number generator relies on a mathematical formula.
A seed acts as a starting point, dictating the sequence of random numbers.
With a fixed seed, NumPy generates identical outputs across multiple runs.
Why Use a Seed?
✔ Reproducibility: Ensures consistent results for testing and debugging.
✔ Consistency: Different users running the same code get identical outputs.
✔ Controlled Randomness: Useful in research, simulations, and machine learning where repeatability matters.

This approach balances randomness and predictability, allowing for both fresh data generation and controlled experiments.







